// 先頭に export をつける
export const countryMap = {
  // あ行
  "Afghanistan": "アフガニスタン",
  "Albania": "アルバニア",
  "Algeria": "アルジェリア",
  "Andorra": "アンドラ",
  "Angola": "アンゴラ",
  "Antigua and Barbuda": "アンティグア・バーブーダ",
  "Argentina": "アルゼンチン",
  "Armenia": "アルメニア",
  "Australia": "オーストラリア",
  "Austria": "オーストリア",
  "Azerbaijan": "アゼルバイジャン",
  "Antarctica": "南極",
  "Iceland": "アイスランド",
  "Ireland": "アイルランド",
  "Israel": "イスラエル",
  "Italy": "イタリア",
  "Iraq": "イラク",
  "Iran": "イラン",
  "India": "インド",
  "Indonesia": "インドネシア",
  "Ukraine": "ウクライナ",
  "Uzbekistan": "ウズベキスタン",
  "United Kingdom": "イギリス",
  "United Arab Emirates": "アラブ首長国連邦",
  "United States": "アメリカ",
  "Uruguay": "ウルグアイ",
  "Ecuador": "エクアドル",
  "Egypt": "エジプト",
  "Estonia": "エストニア",
  "Ethiopia": "エチオピア",
  "El Salvador": "エルサルバドル",
  "Oman": "オマーン",
  "Netherlands": "オランダ",

  // か行
  "Kazakhstan": "カザフスタン",
  "Qatar": "カタール",
  "Canada": "カナダ",
  "Cambodia": "カンボジア",
  "Guyana": "ガイアナ",
  "Cameroon": "カメルーン",
  "South Korea": "韓国",
  "North Korea": "北朝鮮",
  "Cuba": "キューバ",
  "Greece": "ギリシャ",
  "Kyrgyzstan": "キルギス",
  "Guatemala": "グアテマラ",
  "Kuwait": "クウェート",
  "Croatia": "クロアチア",
  "Kenya": "ケニア",
  "Ivory Coast": "コートジボワール",
  "Costa Rica": "コスタリカ",
  "Colombia": "コロンビア",

  // さ行
  "Saudi Arabia": "サウジアラビア",
  "Samoa": "サモア",
  "Sierra Leone": "シエラレオネ",
  "Singapore": "シンガポール",
  "Jamaica": "ジャマイカ",
  "Georgia": "ジョージア",
  "Syria": "シリア",
  "Zimbabwe": "ジンバブエ",
  "Switzerland": "スイス",
  "Sweden": "スウェーデン",
  "Spain": "スペイン",
  "Sri Lanka": "スリランカ",
  "Slovakia": "スロバキア",
  "Slovenia": "スロベニア",
  "Senegal": "セネガル",
  "Serbia": "セルビア",

  // た行
  "Thailand": "タイ",
  "Taiwan": "台湾",
  "Tajikistan": "タジキスタン",
  "Tanzania": "タンザニア",
  "Czech Republic": "チェコ",
  "Chad": "チャド",
  "Tunisia": "チュニジア",
  "Chile": "チリ",
  "Denmark": "デンマーク",
  "Germany": "ドイツ",
  "Dominica": "ドミニカ",
  "Dominican Republic": "ドミニカ共和国",
  "Trinidad and Tobago": "トリニダード・トバゴ",
  "Turkey": "トルコ",

  // な行
  "Nigeria": "ナイジェリア",
  "Namibia": "ナミビア",
  "Nicaragua": "ニカラグア",
  "Niger": "ニジェール",
  "Japan": "日本",
  "New Zealand": "ニュージーランド",
  "Nepal": "ネパール",
  "Norway": "ノルウェー",

  // は行
  "Pakistan": "パキスタン",
  "Panama": "パナマ",
  "Bahamas": "バハマ",
  "Papua New Guinea": "パプアニューギニア",
  "Paraguay": "パラグアイ",
  "Hungary": "ハンガリー",
  "Bangladesh": "バングラデシュ",
  "Bahrain": "バーレーン",
  "Philippines": "フィリピン",
  "Finland": "フィンランド",
  "Bhutan": "ブータン",
  "Brazil": "ブラジル",
  "France": "フランス",
  "French Southern Territories": "仏領南方・南極地域",
  "Bulgaria": "ブルガリア",
  "Brunei": "ブルネイ",
  "Burundi": "ブルンジ",
  "Vietnam": "ベトナム",
  "Venezuela": "ベネズエラ",
  "Belarus": "ベラルーシ",
  "Belize": "ベリーズ",
  "Belgium": "ベルギー",
  "Peru": "ペルー",
  "Poland": "ポーランド",
  "Portugal": "ポルトガル",
  "Honduras": "ホンジュラス",

  // ま行
  "Madagascar": "マダガスカル",
  "Malawi": "マラウイ",
  "Malaysia": "マレーシア",
  "Mali": "マリ",
  "Malta": "マルタ",
  "Micronesia": "ミクロネシア",
  "South Africa": "南アフリカ",
  "Myanmar": "ミャンマー",
  "Mexico": "メキシコ",
  "Mauritius": "モーリシャス",
  "Mauritania": "モーリタニア",
  "Monaco": "モナコ",
  "Maldives": "モルディブ",
  "Moldova": "モルドバ",
  "Morocco": "モロッコ",
  "Mongolia": "モンゴル",
  "Montenegro": "モンテネグロ",

  // や・ら・わ行
  "Jordan": "ヨルダン",
  "Laos": "ラオス",
  "Latvia": "ラトビア",
  "Lithuania": "リトアニア",
  "Libya": "リビア",
  "Liechtenstein": "リヒテンシュタイン",
  "Liberia": "リベリア",
  "Romania": "ルーマニア",
  "Luxembourg": "ルクセンブルク",
  "Rwanda": "ルワンダ",
  "Lesotho": "レソト",
  "Lebanon": "レバノン",
  "Russia": "ロシア"
};